# Generated by Django 4.2.11 on 2024-03-19 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_video_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='timeline',
            field=models.CharField(max_length=20),
        ),
    ]
