# Generated by Django 4.2.11 on 2024-03-17 17:25

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('topic', '0004_remove_post_body_category_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(default=''),
            preserve_default=False,
        ),
    ]
